name: Backend CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Backend
        run: mvn clean install

      - name: Run Backend Tests
        run: mvn test

      - name: Build Docker Image
        run: docker build -t event-ticketing-backend:latest .

  deploy:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Backend to EC2 (Docker)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker pull <your-dockerhub-username>/event-ticketing-backend:latest
            docker stop event-app || true
            docker rm event-app || true
            docker run -d --name event-app -p 8080:8080 <your-dockerhub-username>/event-ticketing-backend:latest